### ISSUE TITLE
Database should allow for large prop values

### ISSUE THREAD

**Issue by guusdk** [igniterealtime/openfire-fastpath-plugin#52]
The FastPath database tables are sometimes used to store snippets of XML. The corresponding columns are currently defined as varchars. I've observed that these can be to small (see exception below). To prevent this, those columns should be modified to be of a clob/text type.

```
2021.02.28 10:22:21 ERROR [pool-29-thread-1]: org.jivesoftware.xmpp.workgroup.spi.JiveLiveProperties - data exception: string data, right truncation;  table: FPWORKGROUPPROP column: PROPVALUE
java.sql.SQLDataException: data exception: string data, right truncation;  table: FPWORKGROUPPROP column: PROPVALUE
        at org.hsqldb.jdbc.JDBCUtil.sqlException(Unknown Source) ~[hsqldb-2.4.1.jar:2.4.1]
        at org.hsqldb.jdbc.JDBCUtil.sqlException(Unknown Source) ~[hsqldb-2.4.1.jar:2.4.1]
        at org.hsqldb.jdbc.JDBCPreparedStatement.fetchResult(Unknown Source) ~[hsqldb-2.4.1.jar:2.4.1]
        at org.hsqldb.jdbc.JDBCPreparedStatement.executeUpdate(Unknown Source) ~[hsqldb-2.4.1.jar:2.4.1]
        at org.apache.commons.dbcp2.DelegatingPreparedStatement.executeUpdate(DelegatingPreparedStatement.java:136) ~[commons-dbcp2-2.6.0.jar:2.6.0]
        at org.apache.commons.dbcp2.DelegatingPreparedStatement.executeUpdate(DelegatingPreparedStatement.java:136) ~[commons-dbcp2-2.6.0.jar:2.6.0]
        at org.jivesoftware.xmpp.workgroup.spi.JiveLiveProperties.insertProperty(JiveLiveProperties.java:126) [fastpath-4.5.0-SNAPSHOT.jar!/:?]
        at org.jivesoftware.xmpp.workgroup.spi.JiveLiveProperties.setProperty(JiveLiveProperties.java:68) [fastpath-4.5.0-SNAPSHOT.jar!/:?]
        at org.jivesoftware.openfire.fastpath.dataforms.FormManager.saveDataForm(FormManager.java:175) [fastpath-4.5.0-SNAPSHOT.jar!/:?]
        at org.jivesoftware.openfire.fastpath.dataforms.FormManager.saveWorkgroupForm(FormManager.java:92) [fastpath-4.5.0-SNAPSHOT.jar!/:?]
        at org.jivesoftware.openfire.fastpath.dataforms.FormManager.createGenericForm(FormManager.java:262) [fastpath-4.5.0-SNAPSHOT.jar!/:?]
        at org.jivesoftware.openfire.fastpath.util.WorkgroupUtils.createWorkgroup(WorkgroupUtils.java:293) [fastpath-4.5.0-SNAPSHOT.jar!/:?]
        at org.jivesoftware.xmpp.workgroup.WorkgroupManager.createDemoWorkgroup(WorkgroupManager.java:957) [fastpath-4.5.0-SNAPSHOT.jar!/:?]
        at org.jivesoftware.xmpp.workgroup.WorkgroupManager.start(WorkgroupManager.java:225) [fastpath-4.5.0-SNAPSHOT.jar!/:?]
        at org.jivesoftware.openfire.component.InternalComponentManager.addComponent(InternalComponentManager.java:192) [xmppserver-4.7.0-SNAPSHOT.jar:4.7.0-SNAPSHOT]
        at org.jivesoftware.openfire.fastpath.FastpathPlugin.workgroupManagerStart(FastpathPlugin.java:110) [fastpath-4.5.0-SNAPSHOT.jar!/:?]
        at org.jivesoftware.openfire.fastpath.FastpathPlugin.initializePlugin(FastpathPlugin.java:88) [fastpath-4.5.0-SNAPSHOT.jar!/:?]
        at org.jivesoftware.openfire.container.PluginManager.loadPlugin(PluginManager.java:683) [xmppserver-4.7.0-SNAPSHOT.jar:4.7.0-SNAPSHOT]
        at org.jivesoftware.openfire.container.PluginMonitor$MonitorTask$4.call(PluginMonitor.java:375) [xmppserver-4.7.0-SNAPSHOT.jar:4.7.0-SNAPSHOT]
        at org.jivesoftware.openfire.container.PluginMonitor$MonitorTask$4.call(PluginMonitor.java:363) [xmppserver-4.7.0-SNAPSHOT.jar:4.7.0-SNAPSHOT]
        at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_282]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_282]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_282]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_282]
Caused by: org.hsqldb.HsqlException: data exception: string data, right truncation;  table: FPWORKGROUPPROP column: PROPVALUE
        at org.hsqldb.error.Error.error(Unknown Source) ~[hsqldb-2.4.1.jar:2.4.1]
        at org.hsqldb.Table.enforceTypeLimits(Unknown Source) ~[hsqldb-2.4.1.jar:2.4.1]
        at org.hsqldb.Table.generateAndCheckData(Unknown Source) ~[hsqldb-2.4.1.jar:2.4.1]
        at org.hsqldb.Table.insertSingleRow(Unknown Source) ~[hsqldb-2.4.1.jar:2.4.1]
        at org.hsqldb.StatementDML.insertSingleRow(Unknown Source) ~[hsqldb-2.4.1.jar:2.4.1]
        at org.hsqldb.StatementInsert.getResult(Unknown Source) ~[hsqldb-2.4.1.jar:2.4.1]
        at org.hsqldb.StatementDMQL.execute(Unknown Source) ~[hsqldb-2.4.1.jar:2.4.1]
        at org.hsqldb.Session.executeCompiledStatement(Unknown Source) ~[hsqldb-2.4.1.jar:2.4.1]
        at org.hsqldb.Session.execute(Unknown Source) ~[hsqldb-2.4.1.jar:2.4.1]
        ... 22 more
Caused by: org.hsqldb.HsqlException: data exception: string data, right truncation
        at org.hsqldb.error.Error.error(Unknown Source) ~[hsqldb-2.4.1.jar:2.4.1]
        at org.hsqldb.error.Error.error(Unknown Source) ~[hsqldb-2.4.1.jar:2.4.1]
        at org.hsqldb.types.CharacterType.convertToTypeLimits(Unknown Source) ~[hsqldb-2.4.1.jar:2.4.1]
        at org.hsqldb.Table.enforceTypeLimits(Unknown Source) ~[hsqldb-2.4.1.jar:2.4.1]
        at org.hsqldb.Table.generateAndCheckData(Unknown Source) ~[hsqldb-2.4.1.jar:2.4.1]
        at org.hsqldb.Table.insertSingleRow(Unknown Source) ~[hsqldb-2.4.1.jar:2.4.1]
        at org.hsqldb.StatementDML.insertSingleRow(Unknown Source) ~[hsqldb-2.4.1.jar:2.4.1]
        at org.hsqldb.StatementInsert.getResult(Unknown Source) ~[hsqldb-2.4.1.jar:2.4.1]
        at org.hsqldb.StatementDMQL.execute(Unknown Source) ~[hsqldb-2.4.1.jar:2.4.1]
        at org.hsqldb.Session.executeCompiledStatement(Unknown Source) ~[hsqldb-2.4.1.jar:2.4.1]
        at org.hsqldb.Session.execute(Unknown Source) ~[hsqldb-2.4.1.jar:2.4.1]
        ... 22 more
```

**Comment by guusdk** [comment]
This appears to affect at the very least "workgroup form" which seems to be missing after the FastPath plugin gets restarted (which makes sense, if it tries to load it from a database where it has not been stored successfully). The absence of this form makes Spark fail (it tries to obtain the form, doesn't receive it from the server, which causes nastiness).

Reconfiguring the form through Openfire's admin console temporarily works around the Spark issue (as it re-inits the form which is supposedly stored in memory somewhere):

![image](https://user-images.githubusercontent.com/4253898/109416851-eb1a8e80-79c0-11eb-821b-9ec6e49d903a.png)
