### ISSUE TITLE
Throws exception pressing on workgroup name

### ISSUE THREAD

**Issue by wrooot** [igniterealtime/openfire-fastpath-plugin#7]
In 4.3.2 when i press on a workgroup name it shows exception:

`Exception:

java.lang.NullPointerException

	at org.jivesoftware.openfire.plugin.fastpath.workgroup_002dqueues_jsp._jspService(workgroup_002dqueues_jsp.java:493)

	at org.apache.jasper.runtime.HttpJspBase.service(HttpJspBase.java:70)

	at javax.servlet.http.HttpServlet.service(HttpServlet.java:790)

	at org.jivesoftware.openfire.container.PluginServlet.handleJSP(PluginServlet.java:395)

	at org.jivesoftware.openfire.container.PluginServlet.service(PluginServlet.java:109)

	at javax.servlet.http.HttpServlet.service(HttpServlet.java:790)

	at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:865)

	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1655)

	at org.jivesoftware.admin.PluginFilter.doFilter(PluginFilter.java:226)

	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1642)

	at org.jivesoftware.admin.AuthCheckFilter.doFilter(AuthCheckFilter.java:216)

	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1642)

	at com.opensymphony.sitemesh.webapp.SiteMeshFilter.obtainContent(SiteMeshFilter.java:129)

	at com.opensymphony.sitemesh.webapp.SiteMeshFilter.doFilter(SiteMeshFilter.java:77)

	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1642)

	at org.jivesoftware.util.LocaleFilter.doFilter(LocaleFilter.java:73)

	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1642)

	at org.jivesoftware.util.SetCharacterEncodingFilter.doFilter(SetCharacterEncodingFilter.java:49)

	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1642)

	at org.jivesoftware.admin.PluginFilter.doFilter(PluginFilter.java:226)

	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1642)

	at org.jivesoftware.admin.AuthCheckFilter.doFilter(AuthCheckFilter.java:216)

	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1634)

	at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:533)

	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:146)

	at org.eclipse.jetty.security.SecurityHandler.handle(SecurityHandler.java:548)

	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:132)

	at org.eclipse.jetty.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:257)

	at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:1595)

	at org.eclipse.jetty.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:255)

	at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1340)

	at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:203)

	at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:473)

	at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:1564)

	at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:201)

	at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1242)

	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:144)

	at org.eclipse.jetty.server.handler.ContextHandlerCollection.handle(ContextHandlerCollection.java:220)

	at org.eclipse.jetty.server.handler.HandlerCollection.handle(HandlerCollection.java:126)

	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:132)

	at org.eclipse.jetty.server.Server.handle(Server.java:503)

	at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:364)

	at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:260)

	at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:305)

	at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:103)

	at org.eclipse.jetty.io.ssl.SslConnection$DecryptedEndPoint.onFillable(SslConnection.java:411)

	at org.eclipse.jetty.io.ssl.SslConnection.onFillable(SslConnection.java:305)

	at org.eclipse.jetty.io.ssl.SslConnection$2.succeeded(SslConnection.java:159)

	at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:103)

	at org.eclipse.jetty.io.ChannelEndPoint$2.run(ChannelEndPoint.java:118)

	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.runTask(EatWhatYouKill.java:333)

	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.doProduce(EatWhatYouKill.java:310)

	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.tryProduce(EatWhatYouKill.java:168)

	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.run(EatWhatYouKill.java:126)

	at org.eclipse.jetty.util.thread.ReservedThreadExecutor$ReservedThread.run(ReservedThreadExecutor.java:366)

	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:765)

	at org.eclipse.jetty.util.thread.QueuedThreadPool$2.run(QueuedThreadPool.java:683)

	at java.lang.Thread.run(Unknown Source)
`

**Comment by wrooot** [comment]
It would be hard to test as Fastpath is not installing on fresh installation.

**Comment by deleolajide** [comment]
I have fixed this issue before. Looks like my fix was lost
